main: com.njdaeger.enhanceddebugstick.plotsquared.PS_Impl
name: ${project.parent.artifactId}-PlotSquared
version: ${project.version}
api-version: 1.13
author: NJDaeger
depend:
  - ${project.parent.artifactId}
  - PlotSquared