# Enable this if you want EnhancedDebugStick to send basic information to bstats.org.
# Data is viewable here: https://bstats.org/plugin/bukkit/EnhancedDebugStick
bstats-integration: true

# When the debug stick is selected or deselected in the players hotbar, a light sound will be
# played to the player indicating the debug stick is being held or not.
sound-on-select: true

# When the player doesn't do something correct with the plugin in game, they will be notified
# with a sound and a message telling them what they did wrong. If this is disabled, the message
# will still send, just not the sound.
sound-on-error: true

# Allow users to set personal settings for themselves without changing this settings file. They would be allowed to
# modify the following:
#   Mode Shifter              - Set a custom shift mode other than the default preference
#   *Double Sneak timeout     - How fast the user must be able to shift to enable/disable the mode shifter
#   Mode Change Cooldown      - How long the user must wait to change modes again.
#   **Sneak Minimum           - Least amount of time the user can sneak to enable/disable the mode shifter
#   **Sneak Maximum           - Most amount of time the user can sneak to still enable/disable the mode shifter
#
# *   The DOUBLE mode shifter must be selected to be an option
# **  The HOLD mode shifter must be selected to be an option
enable-user-preferences: true

# If PlotSquared is installed, settings for it are below.
plotsquared-integration:

  #Enables PlotSquared integration. If enabled, and PS is not installed, the plugin will not act differently. If
  #disabled and PS is installed, the plugin will work as a free for all where players can edit outside of their plots
  enable: false

  # When enabled, this will restrict the usage of the Debug Stick on a plot to only trusted+ people. People who are
  # added temporarily will not be allowed to use the Debug Stick on the plot they were added to. Otherwise, if this is
  # disabled, the temporary people will be able to use the Debug Stick if they have been added, in addition to the other
  # trusted+ members of the plot.
  only-trusted: false

  classic-options:



  freeze-options:



  copy-options:

    copy-outside-of-plot: false

    paste-outside-of-plot: false

#
# Settings for when a player wants to change between debug modes.
#
mode-shift:

  # By default, how should users be changing modes? Possible options are:
  #   COMMAND   - If set to command, the user will need to do /dbs <newMode> to shift modes.
  #   DOUBLE    - If set to double, the user will need to double sneak to enable/disable the mode shifter
  #   HOLD      - If set to hold, the user will need to be holding sneak and not moving to enable/disable the mode shifter
  #
  # Note: users can set their own preference if enabled (see next configuration node)
  # If this node doesn't exist or if the value set is invalid, the default will be DOUBLE
  default-mode-shift-preference: DOUBLE

  # When enabling and disabling the mode shifter, should a sound be played? (only affects the DOUBLE and HOLD preference)
  start-stop-sound: true

  # When going to the next mode, should a sound be played? (only affects the DOUBLE and HOLD preference)
  mode-change-sound: true

  # How long (in milliseconds... 1000 milliseconds = 1 second) should the user wait before being able to change to a
  # different debug mode? In a nutshell, after you disable the mode shifter, by default, 2 seconds can go
  # by where you can spam shift and the mode shifter will not pop up.
  mode-change-cooldown: 2000

  #
  # These options only take effect if the user's (or server if user preferences are disabled) mode shift preference
  # is DOUBLE.
  #
  double-sneak-options:

    # When shifting between modes, how quickly (in milliseconds... 1000 milliseconds = 1 second) must a player double sneak
    # in order for it to be detected as them wanting to change debug modes? Typically anything lower than 500ms is unusable.
    double-sneak-timeout: 750

  #
  # These options only take effect if the user's (or server if the user preferences are disabled) mode shift preference
  # is HOLD.
  #
  hold-sneak-options:

    # When attempting to switch modes, what is the minimum amount of time (in milliseconds... 1000 milliseconds = 1 second)
    # a player needs to hold sneak in order to enable/disable the mode shifter? Default is 1000. If this is less than or
    # equal to 0 the value will go to the default
    sneak-minimum: 1000

    # When attempting to switch modes, what is the maximum amount of time (in milliseconds... 1000 milliseconds = 1 second)
    # a player can hold sneak and still enable/disable the mode shifter? Default is -1 for no time maximum. If this is less
    # than or equal to the shift-minimum value, there will then be no maximum set. So, if the player were to hold shift any
    # amount of time after the shift-minimum time requirement is met- the mode shifter will be enabled/disabled.
    sneak-maximum: 2000



#
# Settings for the classic debug mode. This mode acts like the standard debug stick
#
classic-debug-mode:

  # When looking at a block within a specified distance,
  # should the block properties be displayed to the player?
  display-data-on-look: true

  # If display-data-on-look is enabled, this will limit how far away block data can be seen.
  # If this number is set to 0, the data will not show (equivalent to setting the
  # display-data-on-look to false). If it is set to -1, the limit will default to 10 blocks.
  display-data-distance: 7

  # Enable this if you want CoreProtect to log the edited block.
  # If CoreProtect is not installed, this will do nothing.
  coreprotect-logging: false

  # When the next property is selected (left click) a click will be played to the player
  # indicating the next property has been chosen.
  next-property-sound: true

  # When the next value is selected (right click) a click will be played to the player
  # indicating the next value for the selected property has been chosen.
  next-value-sound: true

  # Enable this if you want to prevent players from editing outside of their PlotSquared plot
  plotsquared-integration: false

#
# Settings for the frozen debug mode. This mode allows the locking of blocks so their properties wont update when a
# block is placed nearby
#
frozen-debug-mode:

  # Outlines the selected block to furthermore express that the block is frozen. This outline will only be shown to
  # whoever is locking the specific block
  outline-selected-block: true

  # When a block is frozen, play a sound to indicate it being frozen
  freeze-sound: true

  # When a block is unfrozen, play a sound to indicate it being unfrozen.
  unfreeze-sound: true

  # When all frozen blocks are unfrozen at the same time, play a sound to indicate it.
  mass-unfreeze-sound: true

  # Enable this if you want to prevent players from editing outside of their PlotSquared plot.
  plotsquared-integration: false



#
# Settings for the copy debug mode. This mode allows the copying and pasting of blockstates (not blocks!) so the common
# properties of the current copied block can be applied to the common properties (which have mismatching values) of another
# block. For example, you have a slab: "stone_slab[type=upper,waterlogged=true]" and you want to copy the properties of
# that block and paste them on another block of similar properties. You copy the slab, and then paste it on a stair block
# which is NOT waterlogged- in this case, the stair block would become waterlogged and nothing else about it would change.
#
copy-debug-mode:

  # When looking at a block within a specified distance,
  # should the block properties be displayed to the player?
  display-data-on-look: true

  # If display-data-on-look is enabled, this will limit how far away block data can be seen.
  # If this number is set to 0, the data will not show (equivalent to setting the
  # display-data-on-look to false). If it is set to -1, the limit will default to 10 blocks.
  display-data-distance: 7

  # When looking at a block to paste properties on, should we always display all the properties
  # of that block or should we only display the applicable properties?
  display-all-properties: true

  # Enable this if you want CoreProtect to log the edited block.
  # If CoreProtect is not installed, this will do nothing.
  coreprotect-logging: false

  # When BlockData is copied (left click) a sound will be played to the player
  # indicating the data was copied
  copy-sound: true

  # When BlockData is pasted (right click) a sound will be played to the player
  # indicating the data was pasted.
  paste-sound: true

  # When the clipblard is cleared (left click air) a sound will be played to the player
  # indicating the clipboard was cleared.
  clear-sound: true