main: com.njdaeger.enhanceddebugstick.blacklist.BL_Impl
name: ${project.parent.artifactId}-BlackList
version: ${project.version}
api-version: 1.13
author: NJDaeger
depend:
  - ${project.parent.artifactId}